try {
 console.log(some);
} catch (error) {
    console.error('Ocurrio un error');
}